### ISSUE TITLE
Make "Mission" folder location configurable

### ISSUE THREAD

**Issue by PatZab** [iso8859-1/Tense#7]
The Mission folder is currently set to be the one under Saved Games/DCS/Missions.
For DCS.openbeta (legacy) it will create a new parallel folder to that one.
best way would be a configurable folder location, thus desired mission folders can be used.

**Comment by iso8859-1** [comment]
Idea:
- use config file if present (ini-file style)
- use Saved Games/DCS/Missions or Saved Games/DCS.openbeta/Missions if exactly one is present
- if both or non are present and no config file is present, fail with error message.
